---
name: Run Unit Tests

'on':
  - pull_request
  - push

jobs:

  testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Install package and dependencies
        run: |
          npm install
      - name: Run Build
        run: npm run build
      - name: Run Tests
        run: ACG_CONFIG="test.json" npm test
